package peg: core@0.1.0;

world host {
    export types;
    export cst;
    export visitor;
    export listener;
}

interface types {
resource url {

}
record text-range {
    head-offset: u32,
    tail-offset: u32,
}
}

interface syntax-tree {
use types.{text-range, language, url};

hack-unused: func() -> notedown-root;

record notedown-root {
    blocks: list<any-blocks>,
    span: text-span,
    path: option<url>
}

//     Heading(Box<HeadingSpan>),
//     Paragraph(Box<ParagraphSpan>),
//     SpaceBreak(Box<ParagraphBreakSpan>),
//     MathBlock(Box<DisplayMathSpan>),
record any-block {
    %type: any-block-type
    span: text-span,
}

variant any-block-type {
    heading(heading-block),
    horizontal-rule(horizontal-rule),
    paragraph(paragraph-block),
    space-break(space-break-block),
    math-block(math-block),
}

record heading-block {
    level: u32,
    title: paragraph-block,
    span: text-span,
}

record paragraph-block {

}


record space-break-block {

}


/// The math text written in the top block
///
/// ### Example
/// ```note
/// $$
/// \int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{
/// 4}
/// $$
/// ```
record math-block {
    %type: math-type
    display: math-display,
    math: string,
    span: text-span,
}
/// The math text written in the paragraph
///
/// ### Example
/// ```note
/// The naunce of the universe is $6.022\times 10^{23}$
/// ```
record math-span {
    display: math-display,
    content: math-type
    math: string,
    span: text-span,
}

variant math-type {
    /// MathML element
    mathml,
    /// TeX ompatible formulas, including `mathjax` and `katex`
    tex,
    asciimath,
}

variant math-display {
    inline,
    block
}


record horizontal-rule {
    marks: string,
    span: text-span,
}



}

interface visitor {

}

interface listener {

}
