package notedown: core@0.1.0;

world host {
    export types;
    export syntax-tree;
}

interface types {
resource url {

}
record text-range {
    head-offset: u32,
    tail-offset: u32,
}
enum notedown-error {
    unknown,
}
}

interface syntax-tree {
use types.{text-range, url};

hack-unused: func() -> notedown-root;

record notedown-root {
    blocks: list<root-item>,
    path: option<url>
}
variant root-item {
    heading(heading-block),
    horizontal-rule(horizontal-rule),
    paragraph(paragraph-block),
    space-break(breakline-block),
    code-block(code-span),
    math-block(math-span),
}
record paragraph-block {
    terms: list<paragraph-item>,
    range: text-range,
}
variant paragraph-item {
    text(normal-text),
    style(styled-text),
    math(math-span),
    code(code-span),
}
record normal-text {
    text: string,
    range: text-range,
}
record styled-text {
    %type: style-type,
    // items: list<paragraph-item>,
    range: text-range,
}
flags style-type {
    bold,
    italic,
    underline,
    strikethrough,
}
// === title block === -----------------------------------------------------------------------------
record heading-block {
    level: u32,
    title: paragraph-block,
    range: text-range,
}
// === line breaks === -----------------------------------------------------------------------------
/// The line break block
/// ```note
/// ===
/// ````
record horizontal-rule {
    lines: u32,
    range: text-range,
}
record breakline-block {
    lines: u32,
    range: text-range,
}
record space-inline {
    space: string,
    range: text-range,
}
// === line breaks === -----------------------------------------------------------------------------
/// The math text written in the paragraph
///
/// ### Example
/// ````note
/// ```code(key: args)
/// ```
/// ````
record code-span {
    action: code-action,
    lines: string,
    range: text-range,
}
variant code-action {
    inine,
    highlight(code-highlight),
}
/// The math text written in the paragraph
///
/// ### Example
/// ````note
/// ```language
/// highlight
/// ```
/// ````
record code-highlight {
    language: string,
    range: text-range,
}
// === line breaks === -----------------------------------------------------------------------------
/// The math text written in the paragraph
///
/// ### Example
/// ```note
/// The naunce of the universe is $6.022\times 10^{23}$
/// ```
record math-span {
    display: math-display,
    content: math-content,
    range: text-range,
}
variant math-display {
    inline,
    block
}
variant math-content {
    /// MathML element
    mathml(string),
    /// TeX ompatible formulas, including `mathjax` and `katex`
    tex(string),
    asciimath(string),
}
// === line breaks === -----------------------------------------------------------------------------





}

interface visitor {

}

interface listener {

}
